apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-watcher
  template:
    metadata:
      labels:
        name: k8s-watcher
    spec:
      serviceAccountName: k8s-watcher
      containers:
        - name: k8s-watcher-operator
          # Replace this with the built image name
          image: sbtech-docker.artifactory.sbtech.com/sbtech-docker/k8s-watcher:latest
          command:
          - k8s-watcher
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-watcher"
      nodeSelector:
        beta.kubernetes.io/os: linux
